### ISSUE TITLE
Question: Relation between three models, sharing same "owner_id"?

### ISSUE THREAD

**Issue by dakipro** [guidocella/eloquent-populator#1]
Hi, not sure how to call it, but in essence I have a category and item - and user who created both of them.
So Item belongsTo one creator_id, and category as well belongsTo one creator_id. 
Item can have one category (doesn't have to), but if it does then both creator_ids needs to be the same for both item and category. 
Meaning, one user created both category and item that belongs to the category (hope that makes sense).

Is there any easy way of doing this with populator, or would I need to manually relate them during/after the seeding?

Thanks!

**Comment by guidocella** [comment]
It should work like this:
```php
$categoryCreators = [];
$categoryId = 1; // Assuming the categories IDs start from 1.

populator()
    ->add(Creator::class, 5)
    ->add(Category::class, 5, [
        'creator_id' => function ($category, $insertedPKs) use (&$categoryCreators, &$categoryId) {
            $creatorId = array_random($insertedPKs[Creator::class]);
            $categoryCreators[$categoryId++] = $creatorId;
            return $creatorId;
        },
    ])
    ->add(Item::class, 5, [
        'creator_id' => function ($item, $insertedPKs) use ($categoryCreators) {
            return $item->category_id
                ? $categoryCreators[$item->category_id]
                : array_random($insertedPKs[Creator::class]);
        }
    ])
    ->seed();
  ```

Or using the category relation, this is simpler but will execute a query for half of the created posts.
```php
$factory->define(Item::class, function () {
    return [
       'creator_id' => function ($item, $insertedPKs) {
            return $item->category_id
                ? $item->category->creator_id
                : array_random($insertedPKs[Creator::class]);
        }
    ];
});
```

But it's easier to do after the seeding if you don't need to do it for every Item created while testing.
```php
Item::whereNotNull('category_id')->update(['creator_id' => DB::raw('(SELECT creator_id FROM categories WHERE id = category_id)')]);
```

**Comment by dakipro** [comment]
Thanks, I tried the first approach, and it is very close. I had to add & on the 
 'creator_id' => function ($item, $insertedPKs) use (&$categoryCreators) {

However, next line return $item->category_id always returns null (I guess item is not yet created?) so condition never goes into the choosing existing categories, meaning it always goes into the array_random($insertedPKs[Creator::class]);

Do you have any suggestions where to proceed?

**Comment by guidocella** [comment]
category_id needs to come before creator_id in the items database table for that to work since Populator will set the closure attributes in the order they appear in the table.

**Comment by dakipro** [comment]
Yes! It is working perfectly! 
Thank you, i have learned a few tricks as well :)
Maybe this could be added/integrated into the library, could be useful

**Comment by guidocella** [comment]
No problem. What exactly do you think should be added to the library?

**Comment by dakipro** [comment]
Good question :)
In ideal scenario lib would recognize that related models share a "common" related model like in the scenario above. Or have it via some config/parameter, not sure what is most practical. 
Also it would be awesome if it could avoid the need for the exact order of the database fields :)

Thus hiding all the logic inside the lib making it much smarter, while the api would look more cleaner/laravel like

populator()
    ->add(Creator::class, 5)
    ->add(Category::class, 5)
    ->add(Item::class, 5)
    ->seed();

Just a thought, it works fine the way you solved it now
