### ISSUE TITLE
README has a typo in an example causing "Call to undefined method"

### ISSUE THREAD

**Issue by atanas-dev** [guidocella/eloquent-populator#2]
```php
$populator->add(User::class)->attachQuantites([Role::class => 5, Club::class => 0]);
```
specifically `attachQuantites` should be `attachQuantities` (last `i` is missing).

A typo is no big deal, of course, but it can be frustrating when copy-pasting examples.

PS:
Thank you for the great library!

**Comment by guidocella** [comment]
Fixed, thanks for the report. :)
