### ISSUE TITLE
Custom User model?

### ISSUE THREAD

**Issue by ozgurkaracam** [guidocella/eloquent-populator#3]
How i use custom User model?

For example

my user migration,

```
Schema::create('users', function (Blueprint $table) {
            $table->increments('id')->unique();
            $table->string('username');
            $table->timestamps();
        });

```
 and user model is

```
protected $table= 'users';

    function posts(){
        return $this->hasMany('App\Post');
    }
    function comments(){
        return $this->hasMany('App\Comment');
    }
```

and when i tried  $populator->add(User::class,10)->seed(); , i see SQLSTATE[42S22]: Column not found: 1054 Unknown column 'email' in 'field list' (SQL: insert into `users` (`created_at`, `email`, `email_verified_at`, `name`, `p 

Please help.

**Comment by guidocella** [comment]
If you don't have it in your table you should remove the email field from the default UserFactory (https://github.com/laravel/laravel/blob/master/database/factories/UserFactory.php).
